[Sun Dec 09 18:29:39.070890 2018] [wsgi:error] [pid 5348:tid 140626203256576] Linux?
[Sun Dec 09 18:37:16.912118 2018] [wsgi:error] [pid 30807:tid 140626203256576] Linux?
[Sun Dec 09 18:39:35.487203 2018] [wsgi:error] [pid 35533:tid 140626203256576] Linux?
[Sun Dec 09 18:46:18.050235 2018] [wsgi:error] [pid 40046:tid 140626203256576] Linux?
[Sun Dec 09 18:55:10.820543 2018] [wsgi:error] [pid 47299:tid 140626203256576] Linux?
[Sun Dec 09 18:56:14.212398 2018] [wsgi:error] [pid 9904:tid 140626203256576] Linux?
[Sun Dec 09 18:58:59.300189 2018] [wsgi:error] [pid 12085:tid 140626203256576] Linux?
[Sun Dec 09 19:01:56.489705 2018] [wsgi:error] [pid 16817:tid 140626203256576] Linux?
[Sun Dec 09 19:04:26.480128 2018] [wsgi:error] [pid 19076:tid 140626203256576] Linux?
[Sun Dec 09 19:06:20.573571 2018] [wsgi:error] [pid 22003:tid 140626203256576] Linux?
[Sun Dec 09 19:07:56.590337 2018] [wsgi:error] [pid 23798:tid 140626203256576] Linux?
[Sun Dec 09 19:12:44.960330 2018] [wsgi:error] [pid 30767:tid 140626203256576] Linux?
[Sun Dec 09 19:14:59.820367 2018] [wsgi:error] [pid 32499:tid 140626203256576] Linux?
[Sun Dec 09 19:16:13.540367 2018] [wsgi:error] [pid 34282:tid 140626203256576] Linux?
[Sun Dec 09 19:18:22.995738 2018] [wsgi:error] [pid 35648:tid 140626203256576] Linux?
[Sun Dec 09 19:24:28.873325 2018] [wsgi:error] [pid 40836:tid 140626203256576] Linux?
[Sun Dec 09 19:26:13.510479 2018] [wsgi:error] [pid 45972:tid 140626203256576] Linux?
[Sun Dec 09 19:31:54.797398 2018] [wsgi:error] [pid 5377:tid 140626203256576] Linux?
[Sun Dec 09 19:35:16.734750 2018] [wsgi:error] [pid 7085:tid 140626203256576] Linux?
[Sun Dec 09 19:41:29.287056 2018] [wsgi:error] [pid 13016:tid 140626203256576] Linux?
[Sun Dec 09 20:34:18.904981 2018] [wsgi:error] [pid 18722:tid 140626203256576] Linux?
[Sun Dec 09 20:35:51.772681 2018] [wsgi:error] [pid 34091:tid 140626203256576] Linux?
[Sun Dec 09 20:43:03.948350 2018] [wsgi:error] [pid 36200:tid 140626203256576] Linux?
[Sun Dec 09 20:55:02.937109 2018] [wsgi:error] [pid 366:tid 140626203256576] Linux?
[Sun Dec 09 20:58:00.960762 2018] [wsgi:error] [pid 12613:tid 140626203256576] Linux?
[Sun Dec 09 20:59:59.790285 2018] [wsgi:error] [pid 15344:tid 140626203256576] Linux?
[Sun Dec 09 21:02:45.126820 2018] [wsgi:error] [pid 20572:tid 140626203256576] Linux?
[Sun Dec 09 21:05:57.395030 2018] [wsgi:error] [pid 22805:tid 140626203256576] Linux?
[Sun Dec 09 21:11:45.248336 2018] [wsgi:error] [pid 25865:tid 140626203256576] Linux?
[Sun Dec 09 21:12:52.132348 2018] [wsgi:error] [pid 34085:tid 140626203256576] Linux?
[Sun Dec 09 21:19:06.473295 2018] [wsgi:error] [pid 35585:tid 140626203256576] Linux?
[Sun Dec 09 21:22:59.192547 2018] [wsgi:error] [pid 43208:tid 140626203256576] Linux?
[Sun Dec 09 21:25:54.725731 2018] [wsgi:error] [pid 48465:tid 140626203256576] Linux?
[Sun Dec 09 21:33:08.440031 2018] [wsgi:error] [pid 3832:tid 140626203256576] Linux?
[Sun Dec 09 21:35:11.276549 2018] [wsgi:error] [pid 11921:tid 140626203256576] Linux?
[Sun Dec 09 21:36:44.161530 2018] [wsgi:error] [pid 13959:tid 140626203256576] Linux?
[Sun Dec 09 21:40:06.717798 2018] [wsgi:error] [pid 16474:tid 140626203256576] Linux?
[Sun Dec 09 21:45:32.721555 2018] [wsgi:error] [pid 25353:tid 140626203256576] Linux?
[Sun Dec 09 21:47:04.135835 2018] [wsgi:error] [pid 26313:tid 140626203256576] Linux?
[Sun Dec 09 21:51:25.962809 2018] [wsgi:error] [pid 33154:tid 140626203256576] Linux?
[Sun Dec 09 21:55:32.458459 2018] [wsgi:error] [pid 35020:tid 140626203256576] Linux?
[Sun Dec 09 21:58:03.170471 2018] [wsgi:error] [pid 38754:tid 140626203256576] Linux?
[Sun Dec 09 22:01:59.321891 2018] [wsgi:error] [pid 40619:tid 140626203256576] Linux?
[Sun Dec 09 22:17:10.146854 2018] [wsgi:error] [pid 47169:tid 140626203256576] Linux?
[Sun Dec 09 22:18:12.554079 2018] [wsgi:error] [pid 14471:tid 140626203256576] Linux?
[Sun Dec 09 22:19:45.509297 2018] [wsgi:error] [pid 15282:tid 140626203256576] Linux?
[Sun Dec 09 22:21:51.579940 2018] [wsgi:error] [pid 19385:tid 140626203256576] Linux?
[Sun Dec 09 22:27:19.099246 2018] [wsgi:error] [pid 22230:tid 140626203256576] Linux?
[Sun Dec 09 22:27:38.966304 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] Request : <QueryDict: {'order_by': ['preview_order'], 'preview_archived': ['false']}>
[Sun Dec 09 22:27:38.966381 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] []
[Sun Dec 09 22:27:38.966401 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] Parameters {'preview_archived': 'false'}
[Sun Dec 09 22:27:38.966412 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] Only []
[Sun Dec 09 22:27:38.966421 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] 
[Sun Dec 09 22:27:38.966426 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] 
[Sun Dec 09 22:27:38.966437 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240]  {'preview_archived': 'false'} 
[Sun Dec 09 22:27:38.966442 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] 
[Sun Dec 09 22:27:38.966448 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] 
[Sun Dec 09 22:27:38.966462 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] Related : []
[Sun Dec 09 22:27:38.968051 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48240] [['answers', 'ForeignKey', 'home', 'answer', True], ['id', 'AutoField', None], ['name', 'CharField', ''], ['factoid', 'TextField', ''], ['order', 'IntegerField', 0], ['component', 'CharField', ''], ['props', 'TextField', ''], ['archived', 'BooleanField', True], ['preview_order', 'IntegerField', 0], ['preview_archived', 'BooleanField', True]]
[Sun Dec 09 22:27:39.125285 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] Request : <QueryDict: {'user': ['5c0d94abdae9f63aceef246b']}>
[Sun Dec 09 22:27:39.125365 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] []
[Sun Dec 09 22:27:39.125387 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] Parameters {'user': '5c0d94abdae9f63aceef246b'}
[Sun Dec 09 22:27:39.125402 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] Only []
[Sun Dec 09 22:27:39.125412 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] 
[Sun Dec 09 22:27:39.125418 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] 
[Sun Dec 09 22:27:39.125432 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]  {'user': '5c0d94abdae9f63aceef246b'} 
[Sun Dec 09 22:27:39.125438 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] 
[Sun Dec 09 22:27:39.125445 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] 
[Sun Dec 09 22:27:39.125462 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] Related : []
[Sun Dec 09 22:27:39.226330 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] Internal Server Error: /api/home/answer/
[Sun Dec 09 22:27:39.226359 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] Traceback (most recent call last):
[Sun Dec 09 22:27:39.226364 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Dec 09 22:27:39.226368 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     response = get_response(request)
[Sun Dec 09 22:27:39.226372 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/base.py", line 126, in _get_response
[Sun Dec 09 22:27:39.226376 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     response = self.process_exception_by_middleware(e, request)
[Sun Dec 09 22:27:39.226384 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/base.py", line 124, in _get_response
[Sun Dec 09 22:27:39.226399 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Dec 09 22:27:39.226403 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/ComponentMadness/modelWebsite/views.py", line 140, in getModelInstanceJson
[Sun Dec 09 22:27:39.226407 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     instanceQuery = model.objects.filter(**parameters)
[Sun Dec 09 22:27:39.226410 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/manager.py", line 82, in manager_method
[Sun Dec 09 22:27:39.226414 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[Sun Dec 09 22:27:39.226418 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/query.py", line 844, in filter
[Sun Dec 09 22:27:39.226422 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     return self._filter_or_exclude(False, *args, **kwargs)
[Sun Dec 09 22:27:39.226425 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/query.py", line 862, in _filter_or_exclude
[Sun Dec 09 22:27:39.226429 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     clone.query.add_q(Q(*args, **kwargs))
[Sun Dec 09 22:27:39.226433 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/sql/query.py", line 1263, in add_q
[Sun Dec 09 22:27:39.226436 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     clause, _ = self._add_q(q_object, self.used_aliases)
[Sun Dec 09 22:27:39.226440 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/sql/query.py", line 1287, in _add_q
[Sun Dec 09 22:27:39.226444 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     split_subq=split_subq,
[Sun Dec 09 22:27:39.226448 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/sql/query.py", line 1225, in build_filter
[Sun Dec 09 22:27:39.226452 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     condition = self.build_lookup(lookups, col, value)
[Sun Dec 09 22:27:39.226456 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/sql/query.py", line 1096, in build_lookup
[Sun Dec 09 22:27:39.226460 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     lookup = lookup_class(lhs, rhs)
[Sun Dec 09 22:27:39.226463 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/lookups.py", line 20, in __init__
[Sun Dec 09 22:27:39.226467 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     self.rhs = self.get_prep_lookup()
[Sun Dec 09 22:27:39.226471 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/fields/related_lookups.py", line 115, in get_prep_lookup
[Sun Dec 09 22:27:39.226475 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     self.rhs = target_field.get_prep_value(self.rhs)
[Sun Dec 09 22:27:39.226484 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/db/models/fields/__init__.py", line 965, in get_prep_value
[Sun Dec 09 22:27:39.226488 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250]     return int(value)
[Sun Dec 09 22:27:39.226494 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] ValueError: invalid literal for int() with base 10: '5c0d94abdae9f63aceef246b'
[Sun Dec 09 22:27:39.226502 2018] [wsgi:error] [pid 22230:tid 140626203256576] [remote 127.0.0.1:48250] 
[Sun Dec 09 22:29:26.375606 2018] [wsgi:error] [pid 27622:tid 140626203256576] Linux?
[Sun Dec 09 22:38:18.063122 2018] [wsgi:error] [pid 31802:tid 140626203256576] Linux?
[Sun Dec 09 22:42:32.096817 2018] [mpm_worker:notice] [pid 33766:tid 140626389944192] AH00298: SIGHUP received.  Attempting to restart
[Sun Dec 09 22:42:32.155127 2018] [mpm_worker:notice] [pid 33766:tid 140626389944192] AH00292: Apache/2.4.37 (Unix) mod_wsgi/4.6.5 Python/3.7 configured -- resuming normal operations
[Sun Dec 09 22:42:32.155167 2018] [core:notice] [pid 33766:tid 140626389944192] AH00094: Command line: '/home/jthiesen1/webapps/norma/apache2/bin/httpd.worker -f /home/jthiesen1/webapps/norma/apache2/conf/httpd.conf'
[Sun Dec 09 22:47:37.909451 2018] [wsgi:error] [pid 44473:tid 140626203256576] Linux?
[Sun Dec 09 22:47:38.154186 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] Request : <QueryDict: {}>
[Sun Dec 09 22:47:38.154231 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] []
[Sun Dec 09 22:47:38.154241 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] Parameters {}
[Sun Dec 09 22:47:38.154248 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] Only []
[Sun Dec 09 22:47:38.154253 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] 
[Sun Dec 09 22:47:38.154256 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] 
[Sun Dec 09 22:47:38.154261 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582]  {} 
[Sun Dec 09 22:47:38.154264 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] 
[Sun Dec 09 22:47:38.154268 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] 
[Sun Dec 09 22:47:38.154274 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] Related : []
[Sun Dec 09 22:47:38.155029 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40582] [['id', 'AutoField', None], ['question', 'CharField', ''], ['answer', 'TextField', ''], ['order', 'IntegerField', 0], ['archived', 'BooleanField', True], ['preview_order', 'IntegerField', 0], ['preview_archived', 'BooleanField', True]]
[Sun Dec 09 22:47:38.434309 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636] Internal Server Error: /favicon.ico/
[Sun Dec 09 22:47:38.434335 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636] Traceback (most recent call last):
[Sun Dec 09 22:47:38.434339 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Dec 09 22:47:38.434344 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]     response = get_response(request)
[Sun Dec 09 22:47:38.434348 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/base.py", line 126, in _get_response
[Sun Dec 09 22:47:38.434352 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]     response = self.process_exception_by_middleware(e, request)
[Sun Dec 09 22:47:38.434357 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/base.py", line 124, in _get_response
[Sun Dec 09 22:47:38.434370 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Dec 09 22:47:38.434375 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/views/decorators/clickjacking.py", line 50, in wrapped_view
[Sun Dec 09 22:47:38.434378 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]     resp = view_func(*args, **kwargs)
[Sun Dec 09 22:47:38.434382 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]   File "/home/jthiesen1/webapps/norma/ComponentMadness/home/views.py", line 27, in Index
[Sun Dec 09 22:47:38.434386 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]     return render(request, "index.html", {})
[Sun Dec 09 22:47:38.434390 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/shortcuts.py", line 36, in render
[Sun Dec 09 22:47:38.434393 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]     content = loader.render_to_string(template_name, context, request, using=using)
[Sun Dec 09 22:47:38.434397 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/template/loader.py", line 61, in render_to_string
[Sun Dec 09 22:47:38.434401 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]     template = get_template(template_name, using=using)
[Sun Dec 09 22:47:38.434405 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/template/loader.py", line 19, in get_template
[Sun Dec 09 22:47:38.434409 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636]     raise TemplateDoesNotExist(template_name, chain=chain)
[Sun Dec 09 22:47:38.434414 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636] django.template.exceptions.TemplateDoesNotExist: index.html
[Sun Dec 09 22:47:38.434423 2018] [wsgi:error] [pid 44473:tid 140626203256576] [remote 127.0.0.1:40636] 
[Sun Dec 09 22:49:34.856437 2018] [wsgi:error] [pid 970:tid 140626203256576] Linux?
[Sun Dec 09 22:54:38.900322 2018] [wsgi:error] [pid 6121:tid 140626203256576] Linux?
[Sun Dec 09 22:57:24.769132 2018] [wsgi:error] [pid 10446:tid 140626203256576] Linux?
[Sun Dec 09 22:58:27.662976 2018] [wsgi:error] [pid 12669:tid 140626203256576] Linux?
[Sun Dec 09 22:58:27.895312 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] Request : <QueryDict: {}>
[Sun Dec 09 22:58:27.932836 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] Internal Server Error: /api/home/userDetails/
[Sun Dec 09 22:58:27.932849 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] Traceback (most recent call last):
[Sun Dec 09 22:58:27.932852 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/apps/config.py", line 165, in get_model
[Sun Dec 09 22:58:27.932856 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]     return self.models[model_name.lower()]
[Sun Dec 09 22:58:27.932858 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] KeyError: 'userdetails'
[Sun Dec 09 22:58:27.932861 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] 
[Sun Dec 09 22:58:27.932864 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] During handling of the above exception, another exception occurred:
[Sun Dec 09 22:58:27.932867 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] 
[Sun Dec 09 22:58:27.932877 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] Traceback (most recent call last):
[Sun Dec 09 22:58:27.932880 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Dec 09 22:58:27.932883 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]     response = get_response(request)
[Sun Dec 09 22:58:27.932886 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/base.py", line 126, in _get_response
[Sun Dec 09 22:58:27.932889 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]     response = self.process_exception_by_middleware(e, request)
[Sun Dec 09 22:58:27.932892 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/base.py", line 124, in _get_response
[Sun Dec 09 22:58:27.932896 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Dec 09 22:58:27.932899 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]   File "/home/jthiesen1/webapps/norma/ComponentMadness/modelWebsite/views.py", line 61, in getModelInstanceJson
[Sun Dec 09 22:58:27.932902 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]     model = apps.get_model(app_label=appLabel, model_name=modelName.replace('_', ''))
[Sun Dec 09 22:58:27.932905 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/apps/registry.py", line 207, in get_model
[Sun Dec 09 22:58:27.932908 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]     return app_config.get_model(model_name, require_ready=require_ready)
[Sun Dec 09 22:58:27.932911 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/apps/config.py", line 168, in get_model
[Sun Dec 09 22:58:27.932914 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388]     "App '%s' doesn't have a '%s' model." % (self.label, model_name))
[Sun Dec 09 22:58:27.932918 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] LookupError: App 'home' doesn't have a 'userDetails' model.
[Sun Dec 09 22:58:27.932923 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:39388] 
[Sun Dec 09 22:59:04.946857 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] Request : <QueryDict: {}>
[Sun Dec 09 22:59:04.946945 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] []
[Sun Dec 09 22:59:04.946965 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] Parameters {}
[Sun Dec 09 22:59:04.946977 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] Only []
[Sun Dec 09 22:59:04.946988 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] 
[Sun Dec 09 22:59:04.946993 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] 
[Sun Dec 09 22:59:04.947004 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910]  {} 
[Sun Dec 09 22:59:04.947009 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] 
[Sun Dec 09 22:59:04.947016 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] 
[Sun Dec 09 22:59:04.947028 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] Related : []
[Sun Dec 09 22:59:04.948354 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40910] [['id', 'AutoField', None], ['user', 'CharField', ''], ['name', 'CharField', '']]
[Sun Dec 09 22:59:05.121687 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914] Internal Server Error: /favicon.ico/
[Sun Dec 09 22:59:05.121704 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914] Traceback (most recent call last):
[Sun Dec 09 22:59:05.121709 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/exception.py", line 34, in inner
[Sun Dec 09 22:59:05.121713 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]     response = get_response(request)
[Sun Dec 09 22:59:05.121716 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/base.py", line 126, in _get_response
[Sun Dec 09 22:59:05.121720 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]     response = self.process_exception_by_middleware(e, request)
[Sun Dec 09 22:59:05.121724 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/core/handlers/base.py", line 124, in _get_response
[Sun Dec 09 22:59:05.121728 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Dec 09 22:59:05.121732 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/views/decorators/clickjacking.py", line 50, in wrapped_view
[Sun Dec 09 22:59:05.121736 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]     resp = view_func(*args, **kwargs)
[Sun Dec 09 22:59:05.121739 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]   File "/home/jthiesen1/webapps/norma/ComponentMadness/home/views.py", line 27, in Index
[Sun Dec 09 22:59:05.121743 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]     return render(request, "index.html", {})
[Sun Dec 09 22:59:05.121746 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/shortcuts.py", line 36, in render
[Sun Dec 09 22:59:05.121750 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]     content = loader.render_to_string(template_name, context, request, using=using)
[Sun Dec 09 22:59:05.121753 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/template/loader.py", line 61, in render_to_string
[Sun Dec 09 22:59:05.121757 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]     template = get_template(template_name, using=using)
[Sun Dec 09 22:59:05.121760 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]   File "/home/jthiesen1/webapps/norma/lib/python3.7/Django-2.1.3-py3.7.egg/django/template/loader.py", line 19, in get_template
[Sun Dec 09 22:59:05.121764 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914]     raise TemplateDoesNotExist(template_name, chain=chain)
[Sun Dec 09 22:59:05.121769 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914] django.template.exceptions.TemplateDoesNotExist: index.html
[Sun Dec 09 22:59:05.121776 2018] [wsgi:error] [pid 12669:tid 140626203256576] [remote 127.0.0.1:40914] 
